<?php

namespace my\comment\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "comment".
 *
 * @property integer $id
 * @property string $user_name
 * @property string $email
 * @property string $url
 * @property string $ip
 * @property string $body
 * @property integer $status
 * @property string $created_at
 * @property integer $entity_id
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_name', 'body', 'entity_id'], 'required'],
            [['body'], 'string'],
            [['status', 'entity_id'], 'integer'],
            [['created_at'], 'safe'],
            [['user_name', 'email', 'ip'], 'string', 'max' => 64],
            [['url'], 'string', 'max' => 250],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_name' => 'User Name',
            'email' => 'Email',
            'url' => 'Url',
            'ip' => 'Ip',
            'body' => 'Body',
            'status' => 'Status',
            'created_at' => 'Created At',
            'entity_id' => 'Entity ID',
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
               // 'createdAtAttribute' => 'create_time',
                'updatedAtAttribute' => false , // 'update_time',
                 'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            // 填充ip字段
            $this->ip = Yii::$app->request->getUserIP() ;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     *   | > --------------------------------------------------------------------------------------- +
     */

    public function fields()
    {
        $fields = parent::fields() ;

        $fields['created_at'] = function ($model) {
            return  Yii::$app->formatter->asDatetime( time() ) ;
            // $model->created_at; // 竟然没有反向填充么
        };

        return $fields ;
    }
}
